a = (input((f'Введите элементы 1 списка:')))
a = a.split(',')
a = set(a)
b = (input((f'Введите элементы 2 списка:')))
b = b.split(',')
b = set(b)
c = a.intersection(b)
a.difference_update(c)
print(a) 